# Generated by Django 3.2.7 on 2021-09-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollments',
            field=models.ManyToManyField(blank=True, null=True, to='group.Group'),
        ),
    ]
